const express = require("express");
const cors = require("cors");
require("dotenv").config();

const app = express();

app.use(cors());
app.use(express.json());

// =========================
// HELPER FUNCTION (Gemini Call)
// =========================
async function callGemini(prompt) {
  try {
    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${process.env.GEMINI_API_KEY}`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          contents: [
            {
              parts: [{ text: prompt }]
            }
          ]
        })
      }
    );

    if (!response.ok) {
      const errorData = await response.json();
      console.error("Gemini API Error:", errorData);
      throw new Error(`API Error: ${response.status} - ${errorData.error?.message || 'Unknown error'}`);
    }

    const data = await response.json();

    if (!data.candidates || data.candidates.length === 0) {
      console.error("No candidates in response:", data);
      throw new Error("No response generated by AI");
    }

    return data.candidates[0]?.content?.parts?.[0]?.text || "No text in response";
  } catch (error) {
    console.error("callGemini error:", error.message);
    throw error;
  }
}

// =========================
// FEATURE 1: FUN FACT
// =========================
app.get("/fun-fact", async (req, res) => {
  try {
    const fact = await callGemini(
      "Tell me one short, interesting fun fact."
    );
    res.json({ fact });
  } catch (error) {
    console.error("Error in /fun-fact:", error);
    res.status(500).json({ fact: `Error: ${error.message}` });
  }
});

// =========================
// FEATURE 2: JOURNAL PROMPT
// =========================
app.post("/journal-prompt", async (req, res) => {
  try {
    const { mood } = req.body;

    if (!mood) {
      return res.status(400).json({ error: "Mood is required" });
    }

    const prompt = await callGemini(
      `Write a short, encouraging journal prompt for someone feeling ${mood}.`
    );

    res.json({ prompt });
  } catch (error) {
    console.error("Error in /journal-prompt:", error);
    res.status(500).json({ prompt: `Error: ${error.message}` });
  }
});

// =========================
// FEATURE 3: HELPER BOT
// =========================
app.get("/joke", async (req, res) => {
  try {
    const result = await callGemini("Tell me a short clean joke.");
    res.json({ result });
  } catch (error) {
    console.error("Error in /joke:", error);
    res.status(500).json({ result: `Error: ${error.message}` });
  }
});

app.get("/motivation", async (req, res) => {
  try {
    const result = await callGemini(
      "Give me a short motivational quote."
    );
    res.json({ result });
  } catch (error) {
    console.error("Error in /motivation:", error);
    res.status(500).json({ result: `Error: ${error.message}` });
  }
});

app.get("/tip", async (req, res) => {
  try {
    const result = await callGemini(
      "Give me one useful life or productivity tip."
    );
    res.json({ result });
  } catch (error) {
    console.error("Error in /tip:", error);
    res.status(500).json({ result: `Error: ${error.message}` });
  }
});

// =========================
// FEATURE 4: GEMINI CHAT (Ask Gemini)
// =========================
app.post("/ask", async (req, res) => {
  try {
    const { question } = req.body;

    if (!question) {
      return res.status(400).json({ answer: "Question is required" });
    }

    const answer = await callGemini(question);
    res.json({ answer });

  } catch (error) {
    console.error("Server error in /ask:", error);
    res.status(500).json({ answer: `Error: ${error.message}` });
  }
});

// =========================
// SERVER START
// =========================
app.listen(5000, () => {
  console.log("Merged Server running at http://localhost:5000");
  console.log("Features: Fun Fact, Journal Prompt, Helper Bot, Gemini Chat");
});
